"""
app/services/pdf_export.py
LectureLens — PDF Export (ReportLab)

Creates:
- Title page
- Notes sections
- Flashcards section
"""

import json
from pathlib import Path
from typing import List, Dict

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4


OUTPUT_DIR = Path("data/exports")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_pdf(
    notes: List[Dict],
    flashcards: List[Dict],
    title: str = "Lecture Notes",
    output_dir: Path = OUTPUT_DIR
) -> Path:
    """
    Generate PDF with notes and flashcards.
    """

    output_dir.mkdir(parents=True, exist_ok=True)

    pdf_path = output_dir / f"{_sanitize_filename(title)}.pdf"

    print(f"[pdf_export] Creating PDF → {pdf_path}")

    doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
    styles = getSampleStyleSheet()

    elements = []

    # -----------------------------------------------------------------------
    # Title Page
    # -----------------------------------------------------------------------
    elements.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by LectureLens", styles["Normal"]))
    elements.append(PageBreak())

    # -----------------------------------------------------------------------
    # Notes Section
    # -----------------------------------------------------------------------
    elements.append(Paragraph("<b>Notes</b>", styles["Heading1"]))
    elements.append(Spacer(1, 12))

    for note in notes:
        timestamp = note.get("timestamp", 0.0)
        title_text = note.get("title", "Topic")
        bullets = note.get("bullets", [])
        tldr = note.get("tldr", "")

        elements.append(
            Paragraph(f"<b>{title_text} ({_fmt_time(timestamp)})</b>", styles["Heading2"])
        )
        elements.append(Spacer(1, 8))

        for b in bullets:
            elements.append(Paragraph(f"• {b}", styles["Normal"]))

        if tldr:
            elements.append(Spacer(1, 6))
            elements.append(Paragraph(f"<i>TL;DR: {tldr}</i>", styles["Italic"]))

        elements.append(Spacer(1, 12))

    elements.append(PageBreak())

    # -----------------------------------------------------------------------
    # Flashcards Section
    # -----------------------------------------------------------------------
    elements.append(Paragraph("<b>Flashcards</b>", styles["Heading1"]))
    elements.append(Spacer(1, 12))

    for card in flashcards:
        q = card.get("question", "")
        a = card.get("answer", "")
        ts = card.get("timestamp", 0.0)

        elements.append(Paragraph(f"<b>Q: {q}</b>", styles["Normal"]))
        elements.append(Paragraph(f"A: {a}", styles["Normal"]))
        elements.append(Paragraph(f"<font size=8>({ _fmt_time(ts) })</font>", styles["Normal"]))
        elements.append(Spacer(1, 12))

    # -----------------------------------------------------------------------
    # Build PDF
    # -----------------------------------------------------------------------
    doc.build(elements)

    print("[pdf_export] PDF created successfully")

    return pdf_path


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _fmt_time(seconds: float) -> str:
    m, s = divmod(int(seconds), 60)
    return f"{m:02d}:{s:02d}"


def _sanitize_filename(name: str, max_len: int = 80) -> str:
    import re
    name = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", name)
    name = re.sub(r"\s+", "_", name.strip())
    return name[:max_len]


# ---------------------------------------------------------------------------
# CLI test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage: python -m app.services.pdf_export <notes.json> <flashcards.json>")
        sys.exit(1)

    notes_path = Path(sys.argv[1])
    flashcards_path = Path(sys.argv[2])

    if not notes_path.exists() or not flashcards_path.exists():
        print("[ERROR] Input files not found")
        sys.exit(1)

    with open(notes_path, "r", encoding="utf-8") as f:
        notes = json.load(f)

    with open(flashcards_path, "r", encoding="utf-8") as f:
        flashcards = json.load(f)

    print("\n[LectureLens] Generating PDF\n")

    try:
        pdf_path = export_pdf(notes, flashcards)

        print(f"\n[OK] PDF saved at: {pdf_path}")

    except Exception as e:
        print(f"\n[ERROR] {e}")
        sys.exit(1)